services:
  - type: web
    name: localservicemanagement
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn LocalServiceManagement.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: LocalServiceManagement.settings
