# Generated by Django 6.0.2 on 2026-03-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
