# Generated by Django 6.0.2 on 2026-03-17 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='professional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professionals.professional'),
            preserve_default=False,
        ),
    ]
