# Generated by Django 6.0.2 on 2026-03-19 02:29 (rewritten to add as nullable)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_professional'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vendor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='bookings',
                to='vendors.vendor',
            ),
        ),
    ]
