# Generated by Django 5.0.2 on 2026-03-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_title_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
