# Generated by Django 6.0.2 on 2026-03-19 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.AddField(
            model_name='vendor',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='services.service'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_earnings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_jobs',
            field=models.IntegerField(default=0),
        ),
    ]
