# Generated by Django 6.0.2 on 2026-03-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendor_address_vendor_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
